apiVersion: apps/v1
kind: Deployment
metadata:
  name: camaraaas-qod-provisioning-api-op-deployment
  namespace: itav-slice-manager-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: camaraaas-qod-provisioning-api-op
  template:
    metadata:
      labels:
        app: camaraaas-qod-provisioning-api-op
    spec:
      serviceAccountName: camaraaas-qod-provisioning-api-op
      containers:
        - name: camaraaas-qod-provisioning-api-op-container
          image: atnog-harbor.av.it.pt/atnog/camaraaas-qod-provisioning-api-op
          command: ["python", "k8s_operator.py"] 
          env:
            - name: LOG_LEVEL
              value: "INFO"
            - name: SLICE_MANAGER_BASE_URL
              value: "http://10.255.28.141:8000"
            - name: CR_GROUP
              value: "av.it.pt"
            - name: CR_VERSION
              value: "v1"
            - name: CR_PLURAL
              value: "networkslice-ues"
      restartPolicy: Always
