apiVersion: av.it.pt/v1
kind: CAMARAaaS-QoDProvisiongAPI
metadata:
  name: example-qod-provisioning
spec:
  messageBroker:
    address: "https://message-broker.example.com"
    port: 9000
    username: "brokerUser" # Replace with Secret if adapted
    password: "brokerPassword" # Replace with Secret if adapted
  serviceUnderControl:
    uuid: "123e4567-e89b-12d3-a456-426614174000"
  camaraAPI:
    url: "https://camara-api.example.com"
    username: "apiUser" # Replace with Secret if adapted
    password: "apiPassword" # Replace with Secret if adapted