apiVersion: av.it.pt/v1
kind: CAMARAaaS-QoDProvisiongAPI
metadata:
  name: simple-qod-provisioning
spec:
  messageBroker:
    url: "https://message-broker.example.com"
    username: "brokerUser" # Replace with Secret if adapted
    password: "brokerPassword" # Replace with Secret if adapted
  serviceUnderControl:
    uuid: "123e4567-e89b-12d3-a456-426614174000"