apiVersion: av.it.pt/v1
kind: CAMARAaaS-QoDProvisiongAPI
metadata:
  name: %s
spec:
  messageBroker:
    url: "%s"
    username: "%s"
    password: "%s"
  serviceUnderControl:
    uuid: "%s"
  camaraAPI:
    url: "%s"
    username: "%s"
    password: "%s"