apiVersion: av.it.pt/v1
kind: CAMARAaaS-QoDProvisiongAPI
metadata:
  name: example-qod-provisioning-with-examples
spec:
  messageBroker:
    address: "https://message-broker.example.com"
    port: 9000
    username: "brokerUser" # Replace with Secret if adapted
    password: "brokerPassword" # Replace with Secret if adapted
  serviceUnderControl:
    uuid: "123e4567-e89b-12d3-a456-426614174000"
  camaraAPI:
    url: "https://camara-api.example.com"
    username: "apiUser" # Replace with Secret if adapted
    password: "apiPassword" # Replace with Secret if adapted
    results: "[{\"device\": {\"ipv4Address\": {\"publicAddress\": \"203.0.113.0\", \"publicPort\": 59765}, \"ipv6Address\": \"2001:db8:85a3:8d3:1319:8a2e:370:7344\", \"networkAccessIdentifier\": \"123456789@domain.com\", \"phoneNumber\": \"+967854321\"}, \"provisioningId\": \"9565c653-7d58-4bf9-9ce5-aa09163021ff\", \"qosProfile\": \"QOS_A\", \"sink\": \"https://endpoint.example.com/sink\", \"sinkCredential\": {}, \"status\": \"AVAILABLE\", \"startedAt\": \"2024-12-14T10:46:47Z\"}]"