apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: camaraaas-qod-provisioning-apis.av.it.pt
spec:
  group: av.it.pt
  names:
    plural: camaraaas-qod-provisioning-apis
    singular: camaraaas-qod-provisioning-api #camaraaas-qod-provisioning
    kind: CAMARAaaS-QoDProvisiongAPI
    shortNames:
      - qod-provisioning-api
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                messageBroker:
                  type: object
                  properties:
                    url:
                      type: string
                    # Todo: The username and password should come from a K8s Secret
                    username:
                      type: string
                    password:
                      type: string
                  required:
                    - url
                    - username
                    - password

                serviceUnderControl:
                  type: object
                  properties:
                    uuid:
                      type: string
                      format: uuid
                  required:
                    - uuid

                camaraAPI:
                  type: object
                  properties:
                    url:
                      type: string
                      default: Yet To Be Configured
                    username:
                      type: string
                      default: Yet To Be Configured
                    password:
                      type: string
                      default: Yet To Be Configured
                    results:
                      type: array
                      default: []
                      items:
                        type: object
                        properties:
                          # Device
                          device:
                            type: object
                            properties:
                              ipv4Address:
                                type: object
                                properties:
                                  publicAddress:
                                    type: string
                                  privateAddress:
                                    type: string
                                  privatePort:
                                    type: integer
                              ipv6Address:
                                type: string
                              phoneNumber:
                                type: string
                                pattern: '^\+[1-9][0-9]{4,14}$'
                              networkAccessIdentifier:
                                type: string
                          # QoS Profile
                          qosProfile:
                            type: string
                          # Sink
                          sink:
                            type: string
                          # Sink Credential
                          sinkCredential:
                            type: object
                            properties:
                              credentialType:
                                type: string
                                enum:
                                  - "PLAIN"
                                  - "ACCESSTOKEN"
                                  - "REFRESHTOKEN"
                          # Provisioning ID
                          provisioningId:
                            type: string
                            format: uuid
                          # Started At
                          startedAt:
                            type: string
                            format: date-time
                          # Status
                          status:
                            type: string
                            enum:
                              - REQUESTED
                              - AVAILABLE
                              - UNAVAILABLE
                          # Status Info 
                          statusInfo:
                            type: string
                            enum:
                              - NETWORK_TERMINATED
                              - DELETE_REQUESTED
              required:
                - serviceUnderControl
                - messageBroker
