# @Author: Eduardo Santos
# @Date:   2024-11-28 10:13:05
# @Last Modified by:   Eduardo Santos
# @Last Modified time: 2024-11-28 12:17:47

version: '3.6'
services:
  service:
    build:
      context: .
    ports:
      - "8000:8000"
    command: uvicorn openapi_server.main:app --host 0.0.0.0 --port 8000 --log-level info
    environment:
      - SQLITE_DB_PATH=/data/sqlite.db  # Environment variable to define SQLite DB path
      - BROKER_ADDRESS=10.255.28.137
      - BROKER_PORT=61613
      - BROKER_USERNAME=artemis
      - BROKER_PASSWORD=artemis
      - SERVICE_UUID=b68492ba-a0b1-46de-beb5-edb3b592f8ba
    volumes:
      - sqlite_data:/data  # Volume to persist SQLite database

volumes:
  sqlite_data:
    driver: local
