apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: network-slice-qod-profiles.av.it.pt
spec:
  group: av.it.pt
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                qodProv:
                  type: object
                  properties:
                    device:
                      type: object
                      properties:
                        phoneNumber:
                          type: string
                        networkAccessIdentifier:
                          type: string
                        ipv4Address:
                          type: object
                          properties:
                            publicAddress:
                              type: string
                            publicPort:
                              type: integer
                        ipv6Address:
                          type: string
                    qosProfile:
                      type: string
                    sink:
                      type: string
                    sinkCredential:
                      type: object
                      additionalProperties: true
                camaraLastRequest:
                  type: string
                camaraResults:
                  type: array
                  items:
                    type: string
              required:
                - qodProv
            status:
              type: object
  scope: Namespaced
  names:
    plural: network-slice-qod-profiles
    singular: network-slice-qod-profile
    kind: NetworkSliceQoDProfile
    shortNames:
      - nsqodp
