apiVersion: apps/v1
kind: Deployment
metadata:
  name: camaraaas-qod-provisioning-api-op-deployment
  namespace: itav-slice-manager-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: camaraaas-qod-provisioning-api-op
  template:
    metadata:
      labels:
        app: camaraaas-qod-provisioning-api-op
    spec:
      serviceAccountName: camaraaas-qod-provisioning-api-op
      containers:
        - name: camaraaas-qod-provisioning-api-op-container
          image: atnog-harbor.av.it.pt/camaraaas/camaraaas-qod-provisioning-api-op
          command: ["python", "k8s_operator.py"] 
          env:
            - name: LOG_LEVEL
              value: "INFO"
            - name: CR_GROUP
              value: "av.it.pt"
            - name: CR_VERSION
              value: "v1"
            - name: CR_PLURAL
              value: "camaraaas-qod-provisioning-apis"
            - name: CAMARA_API_DOCKER_IMAGE
              value: "atnog-harbor.av.it.pt/camaraaas/camaraaas-qod-provisioning-api:latest"
            - name: CAMARA_API_DOCKER_IMAGE_PORT
              value: "8000"

            
      restartPolicy: Always
