apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ include "ue-qod-profile-op-chart.fullname" . }}-deployment'
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "ue-qod-profile-op-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: ue-qod-profile-op
    {{- include "ue-qod-profile-op-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: ue-qod-profile-op
      {{- include "ue-qod-profile-op-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - command:
        - python
        - k8s_operator.py
        env:
        - name: LOG_LEVEL
          value: {{ quote .Values.logLevel }}
        - name: SLICE_MANAGER_BASE_URL
          value: {{ quote .Values.sliceManager.baseUrl }}
        - name: SLICE_MANAGER_USERNAME
          value: {{ quote .Values.sliceManager.username }}
        - name: SLICE_MANAGER_PASSWORD
          value: {{ quote .Values.sliceManager.password }}
        - name: CR_GROUP
          value:  {{ quote .Values.customResource.group }}
        - name: CR_VERSION
          value: {{ quote .Values.customResource.version }}
        - name: CR_PLURAL
          value: {{ quote .Values.customResource.plural }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image:  '{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag | default .Chart.AppVersion }}'
        name: ue-qod-profile-op-container
        resources: {}
      restartPolicy: Always
      serviceAccountName: '{{ include "ue-qod-profile-op-chart.fullname" . }}-svc-account'