apiVersion: apps/v1
kind: Deployment
metadata:
  name: ue-qod-profile-op-deployment
  namespace: itav-slice-manager-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ue-qod-profile-op
  template:
    metadata:
      labels:
        app: ue-qod-profile-op
    spec:
      serviceAccountName: ue-qod-profile-op
      containers:
        - name: ue-qod-profile-op-container
          image: atnog-harbor.av.it.pt/atnog/ue-qod-profile-op
          command: ["python", "k8s_operator.py"] 
          env:
            - name: LOG_LEVEL
              value: "INFO"
            - name: SLICE_MANAGER_BASE_URL
              value: "http://10.255.28.64:8080"
            - name: SLICE_MANAGER_USERNAME
              value: "admin"
            - name: SLICE_MANAGER_PASSWORD
              value: "password"
            - name: CR_GROUP
              value: "av.it.pt"
            - name: CR_VERSION
              value: "v1"
            - name: CR_PLURAL
              value: "ue-qod-profiles"
      restartPolicy: Always
