apiVersion: v1
kind: Service
metadata:
  name: '{{ include "camaraaas-qod-provisioning-api-chart.fullname" . }}-service'
  labels:
    {{- include "camaraaas-qod-provisioning-api-chart.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    app: camaraaas-qod-provisioning-api
    {{- include "camaraaas-qod-provisioning-api-chart.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      # Kubernetes will automatically assign a random NodePort
